# Site settings
title: "Ruby on Rails 教程 - 博客"
author: "安道"
email: your-email@domain.com
description: "Ruby on Rails 教程的最新消息"
baseurl: "http://railstutorial-china.org/blog"
homeurl: "http://railstutorial-china.org"
url: "http://yourdomain.com"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: :title.html

exclude: [".ruby-version", "README.md", "Rakefile", "Gemfile", "Gemfile.lock"]
keep_files: ['.git', '.nojekyll', 'assets']

timezone: '+0800'
